In [81]:
## Section 1: Native DVC API — Programmatic Usage

In [83]:
###  Cell 1: Import and Connect to DVC Project

In [85]:
from dvc.repo import Repo
repo = Repo(".")

In [87]:
### Cell 2: List DVC Stages

import yaml

with open("dvc.yaml", "r") as file:
    dvc_data = yaml.safe_load(file)

for stage_name, details in dvc_data.get('stages', {}).items():
    print(f"Stage: {stage_name}")
    print(f"  Cmd: {details.get('cmd')}")
    print(f"  Deps: {details.get('deps', [])}")
    print(f"  Outs: {details.get('outs', [])}")

Stage: fetch_price
  Cmd: python -c "from src.data_ingestion import record_price; record_price()"
  Deps: ['src/data_ingestion.py']
  Outs: ['data/bitcoin_prices.csv']
Stage: preprocess_and_plot
  Cmd: python -c "from src.preprocess_eda import preprocess, plot_data; df = preprocess(); plot_data(df)"
  Deps: ['data/bitcoin_prices.csv', 'src/preprocess_eda.py']
  Outs: ['Output/bitcoin_price_plot.png', 'data/cleaned_bitcoin.csv']

In [93]:
## Section 2: Wrapper Layer (bitcoin_utils.py)

In [95]:
###  Cell 4: Import Your Wrapper API

from bitcoin_utils import fetch_price, record_price, preprocess, plot_data
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import Image, display

In [97]:
### Cell 5: Record Multiple Price

import time

print("Recording 5 Bitcoin prices...")
for i in range(5):
    record_price("data/bitcoin_prices.csv")
    print(f" Price {i+1}/5 recorded")
    time.sleep(5)
print(" Recording complete!")

Recording 5 Bitcoin prices...
 Price 1/5 recorded
 Price 2/5 recorded
 Price 3/5 recorded
 Price 4/5 recorded
 Price 5/5 recorded
 Recording complete!

In [99]:
### Cell 6: View Latest Raw Records

df = pd.read_csv("data/bitcoin_prices.csv")
df.tail(10)

              timestamp   price
0  2025-05-17T23:07:18Z  103059
1  2025-05-17T23:07:23Z  103059
2  2025-05-17T23:07:28Z  103059
3  2025-05-17T23:07:33Z  103059
4  2025-05-17T23:07:38Z  103055

In [101]:
# Record BTC prices every 10 seconds (12 times = 2 minutes)

print(" Recording live prices for 120 seconds...\n")
for i in range(12):  # 12 records x 10 seconds = 2 minutes
    record_price()
    print(f" Recorded price {i+1}/12")
    time.sleep(10)

print("\n Finished collecting data.")

 Recording live prices for 120 seconds...

Failed to fetch data from CoinGecko API
Price not available.
 Recorded price 1/12
Failed to fetch data from CoinGecko API
Price not available.
 Recorded price 2/12
Failed to fetch data from CoinGecko API
Price not available.
 Recorded price 3/12
Failed to fetch data from CoinGecko API
Price not available.
 Recorded price 4/12
Failed to fetch data from CoinGecko API
Price not available.
 Recorded price 5/12
Failed to fetch data from CoinGecko API
Price not available.
 Recorded price 6/12
 Recorded price 7/12
 Recorded price 8/12
 Recorded price 9/12
 Recorded price 10/12
 Recorded price 11/12
 Recorded price 12/12

 Finished collecting data.

In [105]:
### Cell 1: Import Dependencies and Utility Functions

import pandas as pd
from bitcoin_utils import (
    fetch_price,
    record_price,
    record_live_prices,
    preprocess,
    plot_data
)

In [109]:
### Cell 2: Record a Single Price

record_price()
print("Latest Bitcoin price recorded successfully.")

Failed to fetch data from CoinGecko API
Price not available.
Latest Bitcoin price recorded successfully.

In [111]:
df_raw = pd.read_csv("data/bitcoin_prices.csv")
df_raw.tail(10)

               timestamp   price
1   2025-05-17T23:07:23Z  103059
2   2025-05-17T23:07:28Z  103059
3   2025-05-17T23:07:33Z  103059
4   2025-05-17T23:07:38Z  103055
5   2025-05-17T23:08:46Z  103055
6   2025-05-17T23:08:56Z  103055
7   2025-05-17T23:09:06Z  103055
8   2025-05-17T23:09:16Z  103055
9   2025-05-17T23:09:26Z  103055
10  2025-05-17T23:09:36Z  103047

In [ ]:
# Preprocess using utility logic
# This handles timestamp parsing directly inside the utility

# Run and load cleaned data from utility
df_clean = preprocess()

# Double check type
df_clean['timestamp'] = pd.to_datetime(df_clean['timestamp'], errors='coerce')
df_clean = df_clean.dropna(subset=['timestamp'])

# Show tail of clean